### ISSUE TITLE
Validate-KB quits with error "get_start" on an undefined value

### ISSUE THREAD

**Issue by arunchaganty** [jamesmayfield/ColdStart#17]
A KB we are trying to validate is read without any errors (only warnings for multiple slot fills and inverse relations), but when writing the validated KB, it fails with this exception:
```
Can't call method "get_start" on an undefined value at ColdStart/ColdStartLib.pm line 436.
 at ColdStart/ColdStartLib.pm line 436.
        ProvenanceList::get_start(ProvenanceList=HASH(0x1950df120)) called at ColdStart/CS-ValidateKB-MASTER.pl line 1129
        main::assertion_comparator called at ColdStart/CS-ValidateKB-MASTER.pl line 1397
        main::export_tac(KB=HASH(0x56a2318), HASH(0x3311a80)) called at ColdStart/CS-ValidateKB-MASTER.pl line 1672
```

The NO_ERRORS kb in the test suite does run without error. Our KB is too large to upload here, but [here](https://drive.google.com/open?id=0B6Cq98YIM-eeM1lPUW1fVlVrc3c) is a Google Drive link to the file.

**Comment by shahraj81** [comment]
Hi Arun,

I have committed a change to the develop branch. Could you kindly use code from that branch?

I am planning to announce a release in the next few days with the scorer (which you can preview in the develop branch) after initial testing. This change will be made part of the next release.

Thanks,

Regards,
Shahzad Rajput.

**Comment by shahraj81** [comment]
Also, please close the issue upon confirming if this change fixes your issue. Thanks.

**Comment by arunchaganty** [comment]
Hi @shahraj81,
   Thank you very much for the fix! I can confirm that the validator is now producing output.
